---
layout: default
---
<span style="background-color: white; font-family: &quot;interstate&quot; , &quot;lucida grande&quot; , &quot;lucida sans unicode&quot; , &quot;lucida sans&quot; , &quot;garuda&quot; , &quot;verdana&quot; , &quot;tahoma&quot; , sans-serif; line-height: 37px;"><b>How the Betz Team Helped David Mansfield with His Transaction</b></span><br />
<iframe frameborder="no" height="166" scrolling="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/319638297&amp;color=ff5500&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false" width="100%"></iframe><br />
<span style="background-color: #f2f2f2; color: #333333; font-family: &quot;interstate&quot; , &quot;lucida grande&quot; , &quot;lucida sans unicode&quot; , &quot;lucida sans&quot; , &quot;garuda&quot; , &quot;verdana&quot; , &quot;tahoma&quot; , sans-serif; font-size: 14px;"><br /></span>
<span style="background-color: white;"><span style="color: #333333; font-family: &quot;interstate&quot; , &quot;lucida grande&quot; , &quot;lucida sans unicode&quot; , &quot;lucida sans&quot; , &quot;garuda&quot; , &quot;verdana&quot; , &quot;tahoma&quot; , sans-serif; font-size: 14px;">They were a pleasure to work with. The made everything as simple and easy as possible. I'm going through a very difficult time in my life and they made buying a house as painless as can be. They were very helpful, everything was seamless, and we had a very successful close on the home with very few problems.</span></span><br />
<span style="background-color: white; font-family: &quot;interstate&quot; , &quot;lucida grande&quot; , &quot;lucida sans unicode&quot; , &quot;lucida sans&quot; , &quot;garuda&quot; , &quot;verdana&quot; , &quot;tahoma&quot; , sans-serif; line-height: 37px;"><b>How Wade Betz from Guardian Mortgage helped Randy Ransom</b></span><br />
<iframe frameborder="no" height="166" scrolling="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/311768579&amp;color=ff5500&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false" width="100%"></iframe><br />
<span style="background-color: #f2f2f2; color: #333333; font-family: &quot;interstate&quot; , &quot;lucida grande&quot; , &quot;lucida sans unicode&quot; , &quot;lucida sans&quot; , &quot;garuda&quot; , &quot;verdana&quot; , &quot;tahoma&quot; , sans-serif; font-size: 14px;"><br /></span>
<span style="background-color: white;"><span style="color: #333333; font-family: &quot;interstate&quot; , &quot;lucida grande&quot; , &quot;lucida sans unicode&quot; , &quot;lucida sans&quot; , &quot;garuda&quot; , &quot;verdana&quot; , &quot;tahoma&quot; , sans-serif; font-size: 14px;">It was a very easy process! Wade was very responsive to our needs, and it went well. I was very pleased with the outcome. I've used Wade and his team several times before, and my family has used him several times. We're gonna stick with him forever, and I'd recommend him to anyone because of our good experiences.</span></span><br />
<span style="background-color: #f2f2f2; color: #333333; font-family: &quot;interstate&quot; , &quot;lucida grande&quot; , &quot;lucida sans unicode&quot; , &quot;lucida sans&quot; , &quot;garuda&quot; , &quot;verdana&quot; , &quot;tahoma&quot; , sans-serif; font-size: 14px;"><br /></span>
<span style="background-color: white; font-family: &quot;interstate&quot; , &quot;lucida grande&quot; , &quot;lucida sans unicode&quot; , &quot;lucida sans&quot; , &quot;garuda&quot; , &quot;verdana&quot; , &quot;tahoma&quot; , sans-serif; line-height: 37px;"><b>How Wade Betz from Guardian Mortgage helped Harris Richardson</b></span><br />
<iframe frameborder="no" height="166" scrolling="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/311768584&amp;color=ff5500&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false" width="100%"></iframe>

<br />
<br />
<span style="background-color: white;"><span style="color: #333333; font-family: &quot;interstate&quot; , &quot;lucida grande&quot; , &quot;lucida sans unicode&quot; , &quot;lucida sans&quot; , &quot;garuda&quot; , &quot;verdana&quot; , &quot;tahoma&quot; , sans-serif; font-size: 14px;">I had a great experience. This is actually my fifth loan with Wade! It's always a great experience. As you know, purchasing a home can be very stressful, and they've always made it a no-worries, stress-free experience. They always kept me extremely informed on a weekly basis, and I've always appreciated the way Wade has reached out to me.</span></span><br />
<span style="background-color: white; color: #333333; font-family: &quot;interstate&quot; , &quot;lucida grande&quot; , &quot;lucida sans unicode&quot; , &quot;lucida sans&quot; , &quot;garuda&quot; , &quot;verdana&quot; , &quot;tahoma&quot; , sans-serif; font-size: 14px;"><br /></span> <span style="background-color: white; font-family: &quot;interstate&quot; , &quot;lucida grande&quot; , &quot;lucida sans unicode&quot; , &quot;lucida sans&quot; , &quot;garuda&quot; , &quot;verdana&quot; , &quot;tahoma&quot; , sans-serif; line-height: 37px;"><b>How Wade Betz from Guardian Mortgage helped Katie Masucci</b></span><br />
<iframe frameborder="no" height="166" scrolling="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/311768591&amp;color=ff5500&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false" width="100%"></iframe><br />
<br />
<span style="background-color: white;"><span style="color: #333333; font-family: &quot;interstate&quot; , &quot;lucida grande&quot; , &quot;lucida sans unicode&quot; , &quot;lucida sans&quot; , &quot;garuda&quot; , &quot;verdana&quot; , &quot;tahoma&quot; , sans-serif; font-size: 14px;">Wade Betz was fantastic to work with! He was very responsive, and his team was always open to answering my questions. Most importantly, I got the home of my choice at a great price! I thought I was put in a very good position for a first time home buyer. I've also obtained a lot of knowledge along the way. It was entirely a learning experience, that gave me a resource down the road for mortgage-related questions. I know that they'll be responsive in a timely manner to aid in my questions.</span></span><br />
<span style="background-color: #f2f2f2; color: #333333; font-family: &quot;interstate&quot; , &quot;lucida grande&quot; , &quot;lucida sans unicode&quot; , &quot;lucida sans&quot; , &quot;garuda&quot; , &quot;verdana&quot; , &quot;tahoma&quot; , sans-serif; font-size: 14px;"><br /></span> <span style="background-color: white; font-family: &quot;interstate&quot; , &quot;lucida grande&quot; , &quot;lucida sans unicode&quot; , &quot;lucida sans&quot; , &quot;garuda&quot; , &quot;verdana&quot; , &quot;tahoma&quot; , sans-serif; line-height: 37px;"><b>How Wade Betz from Guardian Mortgage helped Will Stokes</b></span><br />
<span style="background-color: white; font-family: &quot;interstate&quot; , &quot;lucida grande&quot; , &quot;lucida sans unicode&quot; , &quot;lucida sans&quot; , &quot;garuda&quot; , &quot;verdana&quot; , &quot;tahoma&quot; , sans-serif; line-height: 37px;"><b><iframe frameborder="no" height="166" scrolling="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/311768595&amp;color=ff5500&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false" width="100%"></iframe></b></span><br />
<br />
<span style="background-color: white;"><span style="font-family: &quot;interstate&quot; , &quot;lucida grande&quot; , &quot;lucida sans unicode&quot; , &quot;lucida sans&quot; , &quot;garuda&quot; , &quot;verdana&quot; , &quot;tahoma&quot; , sans-serif; font-size: 14px;">Working with Wade was phenomenal! He's professional, the process was easy, and we closed on time without any issues. I couldn't be happier! We were actually on vacation, and I was able to reach him by phone, in the evening, when we had questions about the application, and he was happy to help. He made it all really simple.</span></span><br />
<span style="background-color: #f2f2f2; color: #333333; font-family: &quot;interstate&quot; , &quot;lucida grande&quot; , &quot;lucida sans unicode&quot; , &quot;lucida sans&quot; , &quot;garuda&quot; , &quot;verdana&quot; , &quot;tahoma&quot; , sans-serif; font-size: 14px;"><br /></span> <span style="background-color: white; font-family: &quot;interstate&quot; , &quot;lucida grande&quot; , &quot;lucida sans unicode&quot; , &quot;lucida sans&quot; , &quot;garuda&quot; , &quot;verdana&quot; , &quot;tahoma&quot; , sans-serif; line-height: 37px;"><b>How Wade Betz from Guardian Mortgage helped Wendy Tomlinson</b></span><br />
<iframe frameborder="no" height="166" scrolling="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/300779591&amp;color=ff5500&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false" width="100%"></iframe> <span style="background-color: white; color: #333333; font-family: &quot;interstate&quot; , &quot;lucida grande&quot; , &quot;lucida sans unicode&quot; , &quot;lucida sans&quot; , &quot;garuda&quot; , &quot;verdana&quot; , &quot;tahoma&quot; , sans-serif; font-size: 14px;">&nbsp;</span><br />
<span style="background-color: white; color: #333333; font-family: &quot;interstate&quot; , &quot;lucida grande&quot; , &quot;lucida sans unicode&quot; , &quot;lucida sans&quot; , &quot;garuda&quot; , &quot;verdana&quot; , &quot;tahoma&quot; , sans-serif; font-size: 14px;">I have worked with Wade twice. Once for the purchase of my home, and the second to refinance. It went smoothly both times, and am now in a much better position with a better interest rate! I really loved that I got updates throughout the process. Every few days, he would give me progress reports. I didn’t have to contact him, because he did so first!</span><br />
<br />
<span style="background-color: white; font-family: &quot;interstate&quot; , &quot;lucida grande&quot; , &quot;lucida sans unicode&quot; , &quot;lucida sans&quot; , &quot;garuda&quot; , &quot;verdana&quot; , &quot;tahoma&quot; , sans-serif; line-height: 37px;"><b>How Wade Betz at Guardian Mortgage Helped Barton S Oglesby</b></span><span style="background-color: white;"><iframe frameborder="no" height="166" scrolling="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/282895484&amp;color=297140&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false" width="100%"></iframe></span><br />
<span style="background-color: white;"><br /></span> <span style="background-color: white; color: #333333; font-family: &quot;interstate&quot; , &quot;lucida grande&quot; , &quot;lucida sans unicode&quot; , &quot;lucida sans&quot; , &quot;garuda&quot; , &quot;verdana&quot; , &quot;tahoma&quot; , sans-serif; font-size: 14px; line-height: 19.6px;">"The service was responsive, all the loan terms and expectations were set up front and were followed through with in an exemplary manner . When we got close to closing, the coordination with the title company was very, very good. All of the appointments were made, and everything was at the title company on time and ready to go, there was no delay or surprise. The closing experience was very smooth!"&nbsp;</span><br />
<br />
<b style="font-family: Interstate, &quot;Lucida Grande&quot;, &quot;Lucida Sans Unicode&quot;, &quot;Lucida Sans&quot;, Garuda, Verdana, Tahoma, sans-serif; line-height: 37px;">How Wade Betz at Guardian Mortgage Helped Vayauna Edwards</b><br />
<iframe frameborder="no" height="166" scrolling="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/282896476&amp;color=0c5b25&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false" width="100%"></iframe>

<br />
<div style="color: #333333; font-family: interstate, &quot;lucida grande&quot;, &quot;lucida sans unicode&quot;, &quot;lucida sans&quot;, garuda, verdana, tahoma, sans-serif; font-size: 14px; line-height: 19.6px; margin-bottom: 10px;">
<span style="background-color: white;"><br /></span> <span style="background-color: white;">"Working with Wade was like the best experience I've ever had purchasing anything! Especially a major purchase like a home. I had a lot of questions, he answered every one of them. He was on vacation while I was purchasing my house, I emailed and told him I didn't expect a reply until he returned, and he emailed me back right away, with no hesitation!</span></div>
<div style="color: #333333; font-family: interstate, &quot;lucida grande&quot;, &quot;lucida sans unicode&quot;, &quot;lucida sans&quot;, garuda, verdana, tahoma, sans-serif; font-size: 14px; line-height: 19.6px; margin-bottom: 10px;">
<span style="background-color: white;">He was calm, he made sure that I closed on the day that I needed to close, he worked closely with my agent, and everything went so smoothly. With the title company at close, it was about a 20 minute closing process, it was perfect. Wade is awesome!"</span></div>
